import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import { MicrophoneIcon, SearchIcon } from "@heroicons/react/solid";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Body */}
      <form className="flex flex-col items-center mt-40 ">
        <Image
          src="https://upload.wikimedia.org/wikipedia/commons/6/6e/Google_Name.svg"
          width={300}
          height={100}
          alt="Google Hub Logo"
          objectFit="cover"
        />
        <div className="flex w-full mt-5 mx-auto max-w-[90%] border border-gray-200 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full  items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 text-gray-500 mr-3" />
          <input type="text" className="flex-grow  focus:outline-none" />
          <MicrophoneIcon className="h-5" />
        </div>
        <button>Google Search</button>
        <button>I&apos;m Feeling Lucky</button>
      </form>

      {/* Footer */}
    </div>
  );
}
